#include "minimote_key_type.h"

const char * minimote_key_type_to_string(minimote_key_type type) {
    switch (type) {
        case UP:
            return "UP";
        case DOWN:
            return "DOWN";
        case LEFT:
            return "LEFT";
        case RIGHT:
            return "RIGHT";
        case VOLUME_UP:
            return "VOLUME_UP";
        case VOLUME_DOWN:
            return "VOLUME_DOWN";
        case VOLUME_MUTE:
            return "VOLUME_MUTE";
        case ALT_LEFT:
            return "ALT_LEFT";
        case ALT_RIGHT:
            return "ALT_RIGHT";
        case SHIFT_LEFT:
            return "SHIFT_LEFT";
        case SHIFT_RIGHT:
            return "SHIFT_RIGHT";
        case CTRL_LEFT:
            return "CTRL_LEFT";
        case CTRL_RIGHT:
            return "CTRL_RIGHT";
        case META_LEFT:
            return "META_LEFT";
        case META_RIGHT:
            return "META_RIGHT";
        case ALT_GR:
            return "ALT_GR";
        case CAPS_LOCK:
            return "CAPS_LOCK";
        case ESC:
            return "ESC";
        case TAB:
            return "TAB";
        case SPACE:
            return "SPACE";
        case ENTER:
            return "ENTER";
        case BACKSPACE:
            return "BACKSPACE";
        case CANC:
            return "CANC";
        case PRINT:
            return "PRINT";
        case F1:
            return "F1";
        case F2:
            return "F2";
        case F3:
            return "F3";
        case F4:
            return "F4";
        case F5:
            return "F5";
        case F6:
            return "F6";
        case F7:
            return "F7";
        case F8:
            return "F8";
        case F9:
            return "F9";
        case F10:
            return "F10";
        case F11:
            return "F11";
        case F12:
            return "F12";
        case ZERO:
            return "0";
        case ONE:
            return "1";
        case TWO:
            return "2";
        case THREE:
            return "3";
        case FOUR:
            return "4";
        case FIVE:
            return "5";
        case SIX:
            return "6";
        case SEVEN:
            return "7";
        case EIGHT:
            return "8";
        case NINE:
            return "9";
        case A:
            return "A";
        case B:
            return "B";
        case C:
            return "C";
        case D:
            return "D";
        case E:
            return "E";
        case F:
            return "F";
        case G:
            return "G";
        case H:
            return "H";
        case I:
            return "I";
        case J:
            return "J";
        case K:
            return "K";
        case L:
            return "L";
        case M:
            return "M";
        case N:
            return "N";
        case O:
            return "O";
        case P:
            return "P";
        case Q:
            return "Q";
        case R:
            return "R";
        case S:
            return "S";
        case T:
            return "T";
        case U:
            return "U";
        case V:
            return "V";
        case W:
            return "W";
        case X:
            return "X";
        case Y:
            return "Y";
        case Z:
            return "Z";
        default:
            return "<UNKNOWN>";
    }
}