#ifndef CONF_H
#define CONF_H

#define MINIMOTE_DEFAULT_PORT 50500
#define MINIMOTE_DEFAULT_MOUSE_SENSIBILITY 1.5
#define MINIMOTE_DEFAULT_SCROLL_SENSIBILITY 1
#define MINIMOTE_DEFAULT_SCROLL_REVERSE true

#define MINIMOTE_SERVER_VERSION "0.1"

#endif // CONF_H
