#include "minimote/keys/minimote_key_type_x11_map.h"
#include <X11/Xutil.h>

KeySym KEY_TYPE_X11_MAP[Z + 1] = {
        XK_Up,          // UP
        XK_Down,        // DOWN
        XK_Left,        // LEFT
        XK_Right,       // RIGHT
        NoSymbol,       // VOLUME_UP
        NoSymbol,       // VOLUME_DOWN
        NoSymbol,       // VOLUME_MUTE
        XK_Alt_L,       // ALT_LEFT
        XK_Alt_R,       // ALT_RIGHT
        XK_Shift_L,     // SHIFT_LEFT
        XK_Shift_R,     // SHIFT_RIGHT
        XK_Control_L,   // CTRL_LEFT
        XK_Control_R,   // CTRL_RIGHT
        XK_Super_L,     // META_LEFT
        XK_Super_R,     // META_RIGHT
        XK_ISO_Level3_Shift,     // ALT_GR
        XK_Caps_Lock,   // CAPS_LOCK
        XK_Escape,      // ESC
        XK_Tab,         // TAB
        XK_space,       // SPACE
        XK_Return,      // ENTER
        XK_BackSpace,   // BACKSPACE
        XK_Cancel,      // CANC
        XK_Print,       // PRINT
        XK_F1,          // F1
        XK_F2,          // F2
        XK_F3,          // F3
        XK_F4,          // F4
        XK_F5,          // F5
        XK_F6,          // F6
        XK_F7,          // F7
        XK_F8,          // F8
        XK_F9,          // F9
        XK_F10,         // F10
        XK_F11,         // F11
        XK_F12,         // F12
        XK_0,           // ZERO
        XK_1,           // ONE
        XK_2,           // TWO
        XK_3,           // THREE
        XK_4,           // FOUR
        XK_5,           // FIVE
        XK_6,           // SIX
        XK_7,           // SEVEN
        XK_8,           // EIGHT
        XK_9,           // NINE
        XK_A,           // A
        XK_B,           // B
        XK_C,           // C
        XK_D,           // D
        XK_E,           // E
        XK_F,           // F
        XK_G,           // G
        XK_H,           // H
        XK_I,           // I
        XK_J,           // J
        XK_K,           // K
        XK_L,           // L
        XK_M,           // M
        XK_N,           // N
        XK_O,           // O
        XK_P,           // P
        XK_Q,           // Q
        XK_R,           // R
        XK_S,           // S
        XK_T,           // T
        XK_U,           // U
        XK_V,           // V
        XK_W,           // W
        XK_X,           // X
        XK_Y,           // Y
        XK_Z,           // Z
};