#ifndef CONF_H
#define CONF_H

#define MINIMOTE_SERVER_VERSION "0.3"

#define MINIMOTE_DEFAULT_PORT 50500
#define MINIMOTE_DEFAULT_MOUSE_SENSIBILITY 1.5
#define MINIMOTE_DEFAULT_SCROLL_SENSIBILITY 1
#define MINIMOTE_DEFAULT_SCROLL_REVERSE true

#ifndef MINIMOTE_HOTKEY_INTER_KEYS_DELAY_MS
#define MINIMOTE_HOTKEY_INTER_KEYS_DELAY_MS 5
#endif

#ifndef MINIMOTE_HOTKEY_INTER_SCROLLS_DELAY_MS
#define MINIMOTE_HOTKEY_INTER_SCROLLS_DELAY_MS 20
#endif

#endif // CONF_H